angular.module("myapp")
	.config(config);
function config ($stateProvider,$urlRouterProvider) {
	$urlRouterProvider.otherwise("login");
	$stateProvider
		.state("login",{
			url:"/login",
			templateUrl:"../html/login.html",
			controller:"sub",
			data:{
				title:"登陆页"
			}
			/*,controller:"refresh"*/
		})
		.state("new",{
			url:"/new",
			templateUrl:"../html/new.html",
			data:{
				title:"注册页"
			}
		})
		.state("index",{
			url:"/index",
			templateUrl:"../html/index.html",
			data:{
				title:"首页"
			}
			/*,controller:"refresh"*/
		})
		.state("SecondOne",{
			url:"/SecondOne",
			templateUrl:"../html/SecondOne.html",
			data:{
				title:"问诊"
			}
		})
		.state("ThirdOne",{
			url:"/ThirdOne",
			templateUrl:"../html/ThirdOne.html",
			data:{
				title:"健康商城"
			}
			
		})
		.state("forthOne",{
			url:"/forthOne",
			templateUrl:"../html/forthOne.html",
			data:{
				title:"健康圈"
			}
		})
		.state("MineOne",{
			url:"/MineOne",
			templateUrl:"../html/MineOne.html",
			controller:"data",
			data:{
				title:"我的"
			}
		})
		.state("register",{
			url:"/register",
			templateUrl:"../html/register.html",
			data:{
				title:"一键挂号"
			}
		})
		.state("getMoney",{
			url:"/getMoney",
			templateUrl:"../html/getMoney.html",
			data:{
				title:"步步夺金"
			}
		})
		.state("healthyZB",{
			url:"/healthyZB",
			templateUrl:"../html/healthyZB.html",
			data:{
				title:"健康直播"
			}
		})
		.state("healthyPC",{
			url:"/healthyPC",
			templateUrl:"../html/healthyPC.html",
			controller:"data",
			data:{
				title:"健康评测"
			}
		})
		.state("cpHealthy",{
			url:"/cpHealthy",
			templateUrl:"../html/cpHealthy.html",
			controller:"data",
			data:{
				title:"健康资讯"
			}
		})
		.state("SecondSearchTwo",{
			url:"/SecondSearchTwo",
			templateUrl:"../html/SecondSearchTwo.html",
			data:{
				title:"搜索"
			}
		})
		.state("SecondKid",{
			url:"/SecondKid",
			templateUrl:"../html/SecondKid.html",
			controller:"data",
			data:{
				title:"儿科"
			}
		})
		.state("loseWeight",{
			url:"/loseWeight",
			templateUrl:"../html/loseWeight.html",
			data:{
				title:"瘦下来"
			}
		})
		.state("SumKeepHealthy",{
			url:"/SumKeepHealthy",
			templateUrl:"../html/SumKeepHealthy.html",
			data:{
				title:"夏季养生"
			}
		})
		.state("ThirdList",{
			url:"/ThirdList",
			templateUrl:"../html/ThirdList.html",
			data:{
				title:"分类找药"
			}
		})
		.state("ThirdCard",{
			url:"/ThirdCard",
			templateUrl:"../html/ThirdCard.html",
			data:{
				title:"健康卡"
			}
		})
		.state("ThirdOrder",{
			url:"/ThirdOrder",
			templateUrl:"../html/ThirdOrder.html",
			data:{
				title:"我的订单"
			}
		})
		.state("ThirdBeauty",{
			url:"/ThirdBeauty",
			templateUrl:"../html/ThirdBeauty.html",
			data:{
				title:"美容减肥"
			}
		})
		.state("forthDsic",{
			url:"/forthDsic",
			templateUrl:"../html/forthDsic.html",
			data:{
				title:"发帖圈"
			}
		})
		.state("MineTwo",{
			url:"/MineTwo",
			templateUrl:"../html/MineTwo.html",
			data:{
				title:"健康档案"
			}
		})
		.state("MineTHealth",{
			url:"/MineTHealth",
			templateUrl:"../html/MineTHealth.html",
			data:{
				title:"我的健康圈"
			}
		})
		.state("MineDoctor",{
			url:"/MineDoctor",
			templateUrl:"../html/MineDoctor.html",
			data:{
				title:"我的医生"
			}
		})
		.state("MineFriend",{
			url:"/MineFriend",
			templateUrl:"../html/MineFriend.html",
			data:{
				title:"我的好友"
			}
		})
		.state("MinePlan",{
			url:"/MinePlan",
			templateUrl:"../html/MinePlan.html",
			data:{
				title:"健康计划"
			}
		})
		.state("MineOrders",{
			url:"/MineOrders",
			templateUrl:"../html/MineOrders.html",
			data:{
				title:"我的订单"
			}
		})

}